# Generated by Django 4.2.6 on 2023-10-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='income_source',
        ),
    ]
