# Generated by Django 4.2.6 on 2023-10-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_rename_category_income_income_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomesource',
            options={'verbose_name': 'Fuente', 'verbose_name_plural': 'Fuentes'},
        ),
        migrations.RemoveField(
            model_name='income',
            name='income_source',
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incomes.incomesource', verbose_name='Fuente'),
            preserve_default=False,
        ),
    ]
