# Generated by Django 4.2.6 on 2023-10-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Moneda'),
        ),
    ]
