# Generated by Django 4.2.6 on 2023-10-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date',
        ),
    ]
