# Generated by Django 4.2.6 on 2023-10-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='primary', max_length=12, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
